### PR TITLE
Overhaul of deployment pre-reqs and first attempt to unify the certificates doc

### LINKED ISSUE #1828: Further improvements to certificate docs
From an internal bug filed by @dbarkelew:

The certificate process for VIC is very confusing currently. 

When using intermediate CAs it is unclear if chains are needed in the OVA wizard. I would expect just the signed VIC Appliance certificate in the management portal certificate input and a chain of the intermediate CAs and root CA in the CA field of the install wizard. 

Converting the certificates to the expected format for the management portal wasn't clear. I am thinking this needs a table for converting the following to the components needed. 
Starting -> how to break down to the componet
pksc#12 -> Leaf cert, CA Chain Certificate, Private key in PKCS#8 format
P7b -> Leaf Cert, Private key in PKCS#8 format
RSA/PKCS#1 -> Private key in PKCS#8 format

Then another table covering details required for the certificate for client authentication with the container management portal when adding a VCH. For example the customer found that a certificate did not have the correct key usage and had to be re-issued. Then struggled because container management portal needed RSA format for adding the VCH and was using PKCS#8 because that is what the ova wizard used. The certificate reference is not clear about these requirements. Have a third table discussing the VCH certificate and making sure to convert it properly also would be useful. The certificate reference does start this but is not complete.
https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/vic_cert_reference.html

What also might be useful is a one stop shop start to finish for certificates with VIC. The information seems scattered and customers are not connecting the dots between VCH, VIC Appliance and Client certificates for adding the VHC to the VIC Appliance or use with the docker-client.                   

bug2138800

### PR DESCRIPTION
**Pull request by stuclem**
Fixes #1828, mainly to address @dbarkelew 's comment about creating a "one-stop shop" for certs information. I have attempted to strip all of the theory/requirements content about certs out of the section on the VCH certificate options and into a dedicated VCH Certificates Reference. Also attempted to create a graphic and a certs reference for the appliance.

### CODE REVIEW

**Comment by stuclem** [comment]
This PR is not yet complete (I haven't yet fully understood or addressed the comments from @dbarkelew about cert chains in https://github.com/vmware/vic-product/issues/1828), but I would like to get the ball rolling on the review of the general reorg of the certificates docs. 

Globally, I have moved the conceptual info out of the [VCH Certificate Options](https://github.com/stuclem/vic-product/blob/certchains/docs/user_doc/vic_vsphere_admin/vch_cert_options.md) section in VCH Deployment, and into a dedicated [VCH Certificate Requirements doc](https://github.com/stuclem/vic-product/blob/certchains/docs/user_doc/vic_vsphere_admin/vic_cert_reqs.md). I have also created a [vSphere Integrated Containers Appliance Certificate Requirements](https://github.com/stuclem/vic-product/blob/certchains/docs/user_doc/vic_vsphere_admin/vic_cert_reqs.md) doc. I have placed the two requirements docs at a high level in the Deploy VCHs and Install VIC chapters respectively.

@zjs and @dbarkelew can you please start the review?

**Comment by stuclem** [comment]
@dbarkelew and @zjs I think that I have done as much as I can on this in terms of adding missing content and generally improving the presentation, and so would really appreciate a review of what I've done so far. Just so that I know whether I'm clarifying or muddifying the waters. The key topics in this reorg are the following two, although there are quite a few smaller changes here and there elsewhere: 

- [vSphere Integrated Containers Appliance Certificate Requirements](https://github.com/stuclem/vic-product/blob/certchains/docs/user_doc/vic_vsphere_admin/vic_cert_reqs.md)
- [Virtual Container Host Certificate Requirements](https://github.com/stuclem/vic-product/blob/certchains/docs/user_doc/vic_vsphere_admin/vch_cert_reqs.md)

What we really need as a next step is an example of creating a custom VCH server cert, CA, and client cert. @dbarkelew do you have anything that I can use as inspiration? Thanks!

**Comment by zjs** [comment]
Certificates definitely seem to be a confusing topic for people, so I think unifying the information could be really useful for readers.

A few specific thoughts:

### Organization

I think it would be useful to represent the key user personas (infrastructure administrator, etc.) on the diagram. Each of these personas "initiates" operations in one or more of a few ways (web browser, docker CLI, vic-machine CLI). I think this might give readers a starting point for looking at the diagram: they can start with the thing they're familiar with, and follow lines from there.

I'm not a graphic designer, but maybe have a "zone" for each persona with the clients in it? Something like this, but better:

image

(Disclaimers: These arrows are off the top of my head, for illustration only; not a source-of-truth. Components have been simplified since they're not the point of this example; the OVA would still have sub-components.)

### Certificate information

I think it's really hard to read the detailed certificate information when it's a part of the graphic. It's also not copy-able or searchable. Maybe the graphic could number the communication paths and then have a descriptor for each number in a list/table below?

This may also make it easier to deduplicate information. I think this is similar/related to what you're accomplishing with the colored certificates & key, but approached in a slightly different way.

### OVA/VCH separation

I think the OVA/VCH separation is a bit awkward, and inconsistent with the (good!) idea of unifying the documentation.

Consider someone using `vic-machine create`, who has to deal with several different certificates: the vCenter server certificate (via `--thumbprint`), the VCH server certificate and key, the VCH client certificate(s) and/or CA certificate(s), the Harbor registry root CA, the certificate for any other registries, and perhaps others I'm forgetting. Some of that information is on both diagrams, some is on one (but not the other), and some seems to be absent.

By pulling some information out of the diagram (discussed above), it may be easier to just have one "master" graphic with detailed information _and_ some use-case driven helper text (e.g., a paragraph/section/table that indicates which numbers are relevant to some common/selected workflows like: OVA deployment, VCH creation, container deployment).

I think this is kind of related to the organization topic above.

### Nit-picky stuff

- It seems like the VCH server certificate is missing.
- I think the certificate between the vCenter and the OVA should be the vCenter certificate (not the OVA certificate). (I can't think of workflows where vCenter makes requests to the OVA, but perhaps they exist — If so, we have a bidirectional relationship there.)

**Comment by stuclem** [comment]
Thank you @zjs for this. And @lcastellano for your comment in https://github.com/vmware/vic-product/issues/1828#issuecomment-420570807. I am attempting to construct a new structure. Possible a whole new section of the docs, since the docs are broken down by user role, and the certs pan across those roles...

**Comment by stuclem** [comment]
Apologies for having left this to one side for a while. Given that this PR includes a pretty major content reorg of the deployment pre-reqs, I would really like to merge this before I do the updates for NSX-T support in 1.5. This PR has been hanging around for so long that it has already been overtaken by other content reorgs, I already have conflicts to resolve, and that is only going to get worse. 

So, I would like to merge this now so as to get the new doc structure into master, and then continue the overhaul/review of the certs doc in other PRs. 

@vidya-v, can you please approve this one so that I can fix the conflicts and merge? Thanks!

**Comment by stuclem** [comment]
Thanks @vidya-v. Merging now for continued work in another PR.

**Pull request merged**
