### PR TITLE
Added configuration for forwarding appliance logs to syslog server

### PR DESCRIPTION
**Pull request by vidya-v**
Hi @stuclem 

I added info about the properties under Syslog configuration while deploying the appliance.
Request your review.

Fixes: #2427 

Thanks,
Vidya

### CODE REVIEW

**Comment by stuclem** [comment]
Actually, we need to check whether there is impact on the alternative methods of deploying the appliance:

- https://vmware.github.io/vic-product/assets/files/html/latest/vic_vsphere_admin/deploy_vic_appliance_ovftool.html
- https://vmware.github.io/vic-product/assets/files/html/latest/vic_vsphere_admin/ova_reg_api.html

Similarly, is there an impact on upgrade, e.g. when upgrading an appliance without this option to a version that specifies this option? 
https://vmware.github.io/vic-product/assets/files/html/latest/vic_vsphere_admin/upgrade_appliance.html

We also need to investigate whether the command line options for the upgrade script have added this option.

**Comment by vidya-v** [comment]
Thanks, @stuclem . 
Yes, the ovftool has these parameters - `--prop:syslog_server.syslog_srv_host=“${syslog_srv_host}” --prop:syslog_server.syslog_srv_protocol=“${syslog_srv_protocol}” --prop:syslog_server.syslog_srv_port=“${syslog_srv_port}”'
I included them while documenting the ovftool section. 

I will check if upgrade has an impact.

Thanks,
Vidya

**Comment by vidya-v** [comment]
Hi @stuclem , I discussed this with Jitin. He confirmed that the upgrade and appliance registration don't have ani impact. The upgrade script takes care of this option.

**Comment by vidya-v** [comment]
Thanks, @stuclem ! 
@DanielXiao , can you please review the updates?

Thanks!
Vidya

**Pull request merged**
