### PR TITLE
Added support for 6.7 update 2

### LINKED ISSUE #2248: Document that only 1.5.3 supports 6.7u2
Per https://github.com/vmware/vic-product/issues/2196#issuecomment-448073499, we won't support running 1.4.x on 6.7u2 when it comes out. 

Doc update must wait until 6.7u2 is released, after 1.5.0 GA.

### PR DESCRIPTION
**Pull request by vidya-v**
Hi @stuclem and @DanielXiao ,

Request you to review the updates.
Fixes #2248 

Thanks,
Vidya

### CODE REVIEW

**Comment by vidya-v** [comment]
Thanks, @stuclem , I added update 1 to the list.

**Comment by vidya-v** [comment]
Hi @stuclem and @DanielXiao, if there no more comments, can I merge this?
Thanks,
Vidya

**Comment by stuclem** [comment]
> Hi @stuclem and @DanielXiao, if there no more comments, can I merge this?
> Thanks,
> Vidya

Yep, I think that you can go ahead and merge. Thanks!

**Comment by vidya-v** [comment]
Thanks, @stuclem !

**Pull request merged**
