### PR TITLE
Lost+found workaround removed from doc

### LINKED ISSUE #949: Remove workarounds for lost+found issue from docs
Now that https://github.com/vmware/vic/issues/5777 is fixed, the workarounds that @corrieb added to https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/deploy_multiple_docker_compose.md and https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/deploy_single_containervm.md should be removed.

### PR DESCRIPTION
**Pull request by alextopuzov**
Fixes #949 

@corrieb can you please have a look whether i've removed just enough from the  "Building and Deploying Multi-Container Applications to a Virtual Container Host" topic. I couldn't find any mentions of the workaround in the https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/deploy_single_containervm.md topic, so nothing changed there.

### CODE REVIEW

**Comment by corrieb** [comment]
Yea, the impact that this has on the scripts and text is not immediately obvious. The changes you've made in this doc so far seem good, but we should also modify the mysql script at the top of the doc.

```
# start the database container - specify a subdirectory on the volume as the data dir
docker run -d --name $DB_CTR_NAME --net db-net -v db-data:/var/lib/mysql --cpus 1 -m 2g -e MYSQL_ROOT_PASSWORD=somewordpress -e MYSQL_DATABASE=$DB_PASSWORD -e MYSQL_USER=$DB_USER -e MYSQL_PASSWORD=wordpress mysql:5.7 --datadir=/var/lib/mysql/data
```
should become:
```
# start the database container
docker run -d --name $DB_CTR_NAME --net db-net -v db-data:/var/lib/mysql --cpus 1 -m 2g -e MYSQL_ROOT_PASSWORD=somewordpress -e MYSQL_DATABASE=$DB_PASSWORD -e MYSQL_USER=$DB_USER -e MYSQL_PASSWORD=wordpress mysql:5.7
```

**Comment by corrieb** [comment]
The changes needed to https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/deploy_single_containervm.md are not obvious. 

That file also needs to be updated to reflect the fact that we now have haveged built in to our containervms, so the comments about the workaround are not required. I'll make my own updates to that file and submit a PR

**Comment by corrieb** [comment]
Finally, we should be dry-running any changes we make to these scripts with the target VIC release we're documenting them for to make sure they work. The best way to do this is simply cutting and pasting the docs into a shell and trying them manually. Having automated tests, the danger is that the tests don't get updated with the docs.

**Comment by corrieb** [comment]
I've opened #1302 to address the haveged changes and added in a couple small changes to address the impact of #949

**Comment by stuclem** [comment]
Thanks @corrieb !

**Comment by alextopuzov** [comment]
Thanks @corrieb  ! I've removed the part that you pointed should also go. Merging now.

**Pull request merged**
