### PR TITLE
Merge branch Feature/auto-vic-ui-plugin

### PR DESCRIPTION
**Pull request by wjun**
We switch ui plugin registration from running manual commands of install.sh or upgrade.sh to automation. A set of rest apis are hosted on the VIC appliance fileserver. During the appliance initialization, index.html page will send a post request to the plugin install api, which will prepare the plugin and register the plugin to vCenter. 

A thumbprint verification page is shown to enhance security, e.g. a wrong vCenter or a man-in-the-middle attack.

In case there is an old ui plugin in vCenter already, the new VIC appliance will overwrite the old ui plugin and register a new one.

UI plugin registration is also integrated into upgrade.sh, so the UI plugin can be upgraded as well when running upgrade.sh for VIC appliance upgrade.

With UI plugin auto registration, we do not need the manual ui install/upgrade.sh scripts and vic-ui-* commands anymore, which are removed by PR https://github.com/vmware/vic/pull/8219

Towards: [vmware/vic-product#1432](https://github.com/vmware/vic-product/issues/1432)

### CODE REVIEW

**Comment by zjs** [comment]
In the vic-ui repo, we made some bug fixes to avoid issues with passwords that contained special characters (https://github.com/vmware/vic-ui/pull/558). It looks like some of the affected files were removed from that repo and added to this one as a part of this automation work.

We should see if any of the changes made to the old files in vic-ui are applicable to this PR.

**Comment by zjs** [comment]
It seems like this change invalidates some of the information in [BUILD.md](https://github.com/vmware/vic-product/blob/master/installer/docs/BUILD.md#ci-workflow). We should correct that file to reflect the new relationship between components. (As a reminder, this will require a new PR targeting the feature branch.)

**Comment by morris-jason** [comment]
Same question as in the vic repo: why is this being merged from a fork branch?
Otherwise, looks good.

**Comment by wjun** [comment]
@zjs since ui/install.sh|upgrade.sh|uninstall.sh will be removed after ui registration automation, [vmware/vic-ui#558](https://github.com/vmware/vic-ui/pull/558) will not exist anymore.
@morris-jason The reason I forked is the feature branch has rebase conflict, so I can solve the conflict and merge to master branch directly within one pr. @zjs is this ok, or we usually solve conflict on the feature branch first, and then merge feature branch into master branch? please advice. Thanks.

**Comment by zjs** [comment]
>  fixup! vic-ui robot tests (#1911) 1b59e25 

It seems like this should be submitted to the feature branch, instead of just added directly to this PR.

**Comment by wjun** [comment]
Move to the feature branch directly at https://github.com/vmware/vic-product/pull/1979

**Pull request closed without merging**
