### PR TITLE
Update Harbor UI test (#1633)

### PR DESCRIPTION
**Pull request by andrewtchin**
Cherry picks: 19d8babd
From PR: #1633

### CODE REVIEW

**Comment by mdharamadas1** [comment]
@andrewtchin Looking at the failure screenshot (attached), the Project Repositories page still has table view , whereas this test is updated for card view format. This tells me that either that UI change isn't here or not enabled.

selenium-screenshot-3

**Comment by andrewtchin** [comment]
Still failing in https://ci-vic.vmware.com/vmware/vic-product/4673/9
`--admiral v1.4.0-rc1 --harbor https://storage.googleapis.com/harbor-releases/harbor-offline-installer-v1.5.0-rc2.tgz`

**Comment by reasonerjt** [comment]
@andrewtchin you should be using **admiral v1.4.0-rc2**

**Comment by andrewtchin** [comment]
Works in https://ci-vic.vmware.com/vmware/vic-product/4699

**Pull request merged**
