### PR TITLE
Further updates to the VCH deployment example

### PR DESCRIPTION
**Pull request by stuclem**
Fixes https://github.com/vmware/vic-product/issues/1612.

@dbarkelew does this better reflect the customer experience? @pdaigle can you please take a look too?
To see the topic in its entirety, rather than the diff, go [here](https://github.com/stuclem/vic-product/blob/basicvch/docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md). Thanks!

### CODE REVIEW

**Comment by pdaigle** [comment]
The only comment I have is about the following statement:

    "[...] and add at least a `default` volume store."

Adding a `default` volume store enables the use of Anonymous Volumes. While Anonymous Volumes are useful for dev & test, I would not recommend systematically enabling them for production use (at the very least, users should understand the consequences of doing so). A better recommendation would be to use a named VolumeStore (e.g. myvolume) to map a vSphere Datastore for consumption via the Docker API.

**Comment by stuclem** [comment]
@pdaigle so, should we add notes recommending against using anonymous volumes in production in the following places?

- [Specify Volume Datastores > Anonymous Volumes](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/volume_stores.html#default)
- [Create a Container with a New Anonymous or Named Volume](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_app_dev/using_volumes_with_vic.html#create_container)

If so, how do we reconcile recommending against using anonymous volumes with the statement "some common container images require the presence of a default volume store in order to run" from the first link? 

Also, my understanding is that `dch-photon` creates anonymous volumes, so requires the `default` volume store. Is this indeed the case? 

@dbarkelew and @matthewavery can you chime in here too, please? Thanks!

**Comment by pdaigle** [comment]
The use of anynymous volume is covered in the following section:

[https://vmware.github.io/vic-product/assets/files/html/1.4/vic_app_dev/putting_apps_into_production.html](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_app_dev/putting_apps_into_production.html)

DCH creates two anonymous volumes by default: one for `/certs` and one for `/var/lib/docker`.

image

in `docker inspect`:

image

We can add a recommendation to explicitly create volumes for these which removes the dependency on anonymous volumes:

image

image

Part of this is documented here. We just need to add the '/certs' section with a note that you can also use it to pass certificates in the DCH:

[https://github.com/vmware/vic-product/tree/master/tutorials/dch](https://github.com/vmware/vic-product/tree/master/tutorials/dch)

**Comment by stuclem** [comment]
Further comment from @pdaigle via Slack:

"I just confirmed that DCH fails if no datastore named (default) (i.e. no anonymous) is present.
It’s an OK behavior, I think. We just need to calrify the docs.
SO it does require anonymous by default. Recommendation is to use named volumes unless customer knows what they are doing (some valid use case would be ephemeral docker build hosts for a CI piepline)."

**Pull request merged**
