### PR TITLE
Specified that all VIC engine components run Photon OS 2.0, updated dch-photon version.

### PR DESCRIPTION
**Pull request by stuclem**
Fixes https://github.com/vmware/vic-product/issues/2157

@renmaosheng can you please review or assign a reviewer? Thanks!

### CODE REVIEW

**Comment by stuclem** [comment]
@DanielXiao I believe that you implemented the migration to Photon OS 2.0. Can you please review this doc PR? Thanks!

**Comment by DanielXiao** [comment]
All looks good beside the DCH part. Please see my comments.

**Comment by stuclem** [comment]
Thanks @DanielXiao, I have updated the version of `dch-photon` per your comment.

Also fixes https://github.com/vmware/vic-product/issues/2217 and updates links to the Photon OS docs.

**Comment by stuclem** [comment]
Thanks @DanielXiao!

**Pull request merged**
