### PR TITLE
Clarified that you cannot use --insecure-registry with VIC Registry.

### PR DESCRIPTION
**Pull request by stuclem**
Fixes https://github.com/vmware/vic-product/issues/646.

@gigawhitlocks, @emlin and @reasonerjt can you please confirm that this is correct and review?

### CODE REVIEW

**Comment by emlin** [comment]
@chengwang86 @sflxn please help to confirm

**Comment by chengwang86** [comment]
@stuclem @emlin We had an issue with http connection to an insecure-registry https://github.com/vmware/vic/issues/5622 but it was fixed by @gigawhitlocks . We also have an integration test for insecure-registry with http.

**Comment by stuclem** [comment]
@chengwang86 pointed me to https://github.com/vmware/vic/blob/master/tests/test-cases/Group11-Upgrade/11-03-Upgrade-InsecureRegistry.robot#L93, in which we install a harbor instance with http, then deploy the VCH with --insecure-registry. So, I might not be merging this PR :)

**Comment by stuclem** [comment]
So, it turns out that @chengwang86 is talking about connecting VCHs to standalone Harbor registries, not to the VIC Registry that is deployed with the OVA. My belief is still that the official VIC Registry is HTTPS only. @reasonerjt or @hainingzhang can you please confirm?

**Comment by mdubya66** [comment]
we only support the harbor that is on the OVA. only https is supported with that version.

**Comment by stuclem** [comment]
Thanks @mdubya66. In light of @mdubya66 's comment above, @chengwang86, @gigawhitlocks, and @emlin can you please re-review this PR? Thanks!

**Comment by stuclem** [comment]
Thanks @chengwang86 !

**Pull request merged**
