### PR TITLE
Add VIC install tutorial

### PR DESCRIPTION
**Pull request by guillierf**

### CODE REVIEW

**Comment by andrewtchin** [comment]
@guillierf Actually can you remove the zip file from the PR? `git rm tutorials/install-tutorial/images.zip`, `git commit -am "Remove zip file"`, `git push`
If there aren't any more changes to the guide itself, I'll merge this once the zip is removed

**Comment by guillierf** [comment]
@andrewtchin 
done

let me know if I need to do additional operations

**Comment by andrewtchin** [comment]
Thanks @guillierf!

**Comment by guillierf** [comment]
thanks @andrewtchin !

**Pull request merged**
